//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public int UserId { get; set; }
        public int DisctrictId { get; set; }
        public int MunicipalityId { get; set; }
        public string CurrentLocation { get; set; }
        public string AddressType { get; set; }
    
        public virtual District District { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual User User { get; set; }
    }
}
