//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int BillId { get; set; }
        public double ServiceCharge { get; set; }
        public Nullable<double> TravellingCost { get; set; }
        public Nullable<double> Discount { get; set; }
        public double TotalCharge { get; set; }
        public string CustomerAcceptance { get; set; }
        public string PaidStatus { get; set; }
        public System.DateTime IssuedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
