//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int ServiceProvider { get; set; }
        public int Customer { get; set; }
        public string ServiceType { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string CustomerAddress { get; set; }
        public string ProblemDescription { get; set; }
        public string ProblemImage { get; set; }
        public string SpecialistAcceptance { get; set; }
        public string CompletedStatus { get; set; }
        public Nullable<int> BillId { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
