//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string ContactNumber { get; set; }
        public string ContactType { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
