//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackReply
    {
        public int ReplyId { get; set; }
        public int FeedbackId { get; set; }
        public string Reply { get; set; }
        public System.DateTime ReplyDate { get; set; }
        public int ReplyBy { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual User User { get; set; }
    }
}
