//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastMessage
    {
        public int LastChatId { get; set; }
        public int ParticipantOne { get; set; }
        public int ParticipantTwo { get; set; }
        public string LastMessage1 { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Seen { get; set; }
        public string SenderId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
