//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public int ReportedBy { get; set; }
        public int ReportedTo { get; set; }
        public string ReportDescription { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
