//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        public int RespondedId { get; set; }
        public int RespondedBy { get; set; }
        public int RespondedTo { get; set; }
    
        public virtual Problem Problem { get; set; }
        public virtual User User { get; set; }
    }
}
