//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roof_Care.ExmxDbSets
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserState
    {
        public int StateId { get; set; }
        public int ServiceProviderId { get; set; }
        public string Completed { get; set; }
        public string OnBudget { get; set; }
        public string OnTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
